### ISSUE TITLE
Move Class: Invalid propagation!

### ISSUE THREAD

**Issue by seyyedaliayati** [m-zakeri/CodART#63]
**Describe the bug**
After moving class from one package to another, all imports should fix and refer to the target package, but this script deletes all the imports from source package while it's required to delete or replace some of them. For example, consider this scenario:

In the User class we used MoveClass (from source_package):
```
import source_package.MoveClass;
import source_package.SourceClass;

public class User {
    SourceClass sourceClass;
    MoveClass moveClass;
    
    public User(){
        this.sourceClass = new SourceClass();
        this.moveClass = new MoveClass();
        sourceClass.method_for_move();
        System.out.println(SourceClass.field_for_move);
        System.out.println(moveClass.getName());
    }
}
```
After moving MoveClass from source_package to target_package the User class changes as follow:
```
import target_package.MoveClass;
public class User {
    SourceClass sourceClass;
    MoveClass moveClass;
    
    public User(){
        this.sourceClass = new SourceClass();
        this.moveClass = new MoveClass();
        sourceClass.method_for_move();
        System.out.println(SourceClass.field_for_move);
        System.out.println(moveClass.getName());
    }
}
```
It's seen that it removed all the imports from source_package while it should remove just imports related to MoveClass, so our project is not runnable any more!

```
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
        The field SourceClass.field_for_move is not visible

        at User.<init>(User.java:10)
        at App.main(App.java:4)
```
**File Path**
refactorings/move_class.py

**Comment by seyyedaliayati** [comment]
Fixed in https://github.com/m-zakeri/CodART/commit/e4b1630ff725693fa7610c389c64681346401d44
